# Generated by Django 2.0.3 on 2018-03-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.CharField(default=0, max_length=255, verbose_name='task'),
        ),
        migrations.AddField(
            model_name='todo',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='Resolved?'),
        ),
    ]
