# Generated by Django 2.0.3 on 2018-04-01 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20180330_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-priority', 'title']},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='content',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default='Todo', max_length=250),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High')], default=2),
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_list',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='todo.List'),
        ),
    ]
