# Generated by Django 2.0.3 on 2018-04-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20180401_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todo_list',
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(default='Todo <built-in function id>', max_length=250),
        ),
    ]
